package com.itskidan.tscapp.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0D305F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF355283)
val onPrimaryContainerLight = Color(0xFFF1F4FF)
val secondaryLight = Color(0xFF545E74)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDCE6FF)
val onSecondaryContainerLight = Color(0xFF404A5F)
val tertiaryLight = Color(0xFF48214E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF6E4372)
val onTertiaryContainerLight = Color(0xFFFFF0FB)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF9FD)
val onBackgroundLight = Color(0xFF1A1B1F)
val surfaceLight = Color(0xFFFAF9FD)
val onSurfaceLight = Color(0xFF1A1B1F)
val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF43474F)
val outlineLight = Color(0xFF747780)
val outlineVariantLight = Color(0xFFC4C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3034)
val inverseOnSurfaceLight = Color(0xFFF1F0F5)
val inversePrimaryLight = Color(0xFFABC7FF)
val surfaceDimLight = Color(0xFFDAD9DE)
val surfaceBrightLight = Color(0xFFFAF9FD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3F8)
val surfaceContainerLight = Color(0xFFEEEDF2)
val surfaceContainerHighLight = Color(0xFFE9E7EC)
val surfaceContainerHighestLight = Color(0xFFE3E2E6)

val primaryDark = Color(0xFFABC7FF)
val onPrimaryDark = Color(0xFF0D305F)
val primaryContainerDark = Color(0xFF1A3969)
val onPrimaryContainerDark = Color(0xFFB3CCFF)
val secondaryDark = Color(0xFFBCC6DF)
val onSecondaryDark = Color(0xFF263044)
val secondaryContainerDark = Color(0xFF353F53)
val onSecondaryContainerDark = Color(0xFFC9D4EC)
val tertiaryDark = Color(0xFFEAB5EC)
val onTertiaryDark = Color(0xFF48214E)
val tertiaryContainerDark = Color(0xFF532B58)
val onTertiaryContainerDark = Color(0xFFF1BBF2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121317)
val onBackgroundDark = Color(0xFFE3E2E6)
val surfaceDark = Color(0xFF121317)
val onSurfaceDark = Color(0xFFE3E2E6)
val surfaceVariantDark = Color(0xFF43474F)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E909A)
val outlineVariantDark = Color(0xFF43474F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E6)
val inverseOnSurfaceDark = Color(0xFF2F3034)
val inversePrimaryDark = Color(0xFF425E90)
val surfaceDimDark = Color(0xFF121317)
val surfaceBrightDark = Color(0xFF38393D)
val surfaceContainerLowestDark = Color(0xFF0D0E11)
val surfaceContainerLowDark = Color(0xFF1A1B1F)
val surfaceContainerDark = Color(0xFF1E1F23)
val surfaceContainerHighDark = Color(0xFF292A2D)
val surfaceContainerHighestDark = Color(0xFF343538)

val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)
